export const BASE_URL = 'http://localhost:8082'; // Registration service port
export const GET_USER_BY_ID = '/api/auth/users';
export const LOGIN = '/api/auth/login';
export const REGISTER = '/api/auth/register';
export const LOGOUT = '/api/auth/logout';
export const DEPOSIT = '/api/transaction/deposit';
export const WITHDRAW = '/api/transaction/withdraw';
export const TRANSFER = '/api/transaction/transfer';
export const BALANCE = '/api/transaction/balance';
export const STATEMENT = '/api/transaction/statement';
export const GETUSER = '/api/user';
export const RESET_PASSWORD = "/reset-password";
export const VERIFY_USER = "/verify-user";
